app/views.py
from flask import Blueprint, Flask, render_template, request, redirect, \
    url_for, jsonify
import datetime
import os
# Database model
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from models import Base, Application, Suggestions
from flask import session as login_session
from controllers import *
from forms import ApplicationAddForm, ApplicationEditForm, SearchForm
apply_blueprint = Blueprint('app', __name__)
suggest_blueprint = Blueprint('suggest', __name__)


@apply_blueprint.route('/', methods=['GET','POST'])
def home():
    return render_template('applications.html', applications=get_applications('desc'))


@apply_blueprint.route('/last_week')
def past_week():
    return render_template('applications.html', applications=past_week_applications())


@apply_blueprint.route('/order/company_name/desc')
def sort_by_company_desc():
    return render_template('applications.html', applications=sort_applications_by_company('desc'))

@apply_blueprint.route('/order/company_name/asc')
def sort_by_company():
    return render_template('applications.html', applications=sort_applications_by_company('asc'))


@apply_blueprint.route('/add/application', methods=['GET', 'POST'])
def add_app():
    form = ApplicationAddForm()
    if request.method == 'POST':

        doa = map(int, request.form['date_apply'].split('-'))
        date_apply = datetime.date(doa[0], doa[1], doa[2])
        applcation = Application(company_name=request.form['company_name'],
                                 date_apply=date_apply,
                                 position=request.form['position'],
                                 location=request.form['location'],
                                 next_step=request.form['next_step'],
                                 contact=request.form['contact'],
                                 job_board=request.form['job_board'],
                                 notes=request.form['notes'])
        session.add(applcation)
        session.commit()
        return redirect(url_for('app.home'))
    else:
        return render_template('addApply.html', form=form)


@apply_blueprint.route('/edit/application/<int:id>', methods=['POST', 'GET'])
def edit_app(id):
    form = ApplicationEditForm()
    app = get_application(id)
    if request.method == 'POST':
        doa = map(int, request.form['date_apply'].split('-'))
        date_apply = datetime.date(doa[0], doa[1], doa[2])
        app.company_name = request.form['company_name']
        app.date_apply = date_apply
        app.position = request.form['position']
        app.location = request.form['location']
        app.next_step = request.form['next_step']
        app.contact = request.form['contact']
        app.job_board = request.form['job_board']
        app.notes = request.form['notes']
        session.add(app)
        session.commit()
        return redirect(url_for('app.home'))
    else:
        return render_template('editApply.html',
                               apply=app,
                               form=form)


@apply_blueprint.route('/info/<int:app_id>')
def more_info(app_id):
    return render_template('moreInfo.html', app=get_application(app_id))

app/templates/addApply.html
{% extends 'index.html' %} {% import 'macros.html' as macros %} {% block content %} {% if 'username' in session %}

<div class="container apps">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3 panel panel-default">
      <legend>Add Applicaion</legend>
      {% call macros.render_form(form, action_url=url_for('app.add_app'), action_text="Add Application", class_="form-horizontal") %}
      <div class="col-md-6">
        {{ macros.input(form.company_name, type='text') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.date_apply, type='date') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.position, type='select') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.location, type='text') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.next_step, type='text') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.contact, type='text') }}
      </div>
      <div class="col-md-12">
        {{ macros.input(form.job_board, type='text') }}
      </div>

      <div class="col-md-12">
        {{ macros.render_textarea(form.notes)}}
      </div>
      <div class="col-md-12 text-center">
      {% endcall %}
      </div>

    </div>
  </div>




</div>{% else %}
<h1>You be here. Your IP has been logged</h1> {% endif %}
</div>

{% endblock %}

app/templates/applications.html
{% extends 'index.html' %} {% import 'macros.html' as macros %} {% block content %}
<section class='apps'>
  <div class="containter">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3"><strong>Company Name</strong>    
	    <a href="{{url_for('app.sort_by_company')}}"><span class="glyphicon glyphicon-chevron-up"></span></a>


	    <a href="{{url_for('app.sort_by_company_desc')}}"><span class="glyphicon glyphicon-chevron-down"></span></a>
        </div>
        <div class="col-md-1"><strong>Date</strong></div>
        <div class="col-md-4"><strong>Position</strong></div>
        <div class="col-md-3"><strong>Location</strong></div>
        <div class="col-md-1"><strong>Actions</strong></div>
      </div>
      {% for app in applications %}
      <div class="col-md-12">
        <div class="col-md-3">{{ app.company_name}}</div>
        <div class="col-md-1">{{ app.date_apply.strftime('%m-%d')}}</div>
        <div class="col-md-4">{{ app.position}}</div>
        <div class="col-md-3">{{ app.location}}</div>
        <div class="col-md-1"><a href="{{url_for('app.more_info', app_id=app.id)}}" >More Info</a> 
         </div>
      </div>
      {% endfor %}
    </div>
  </div>

  {% if 'username' in session %}
  <a href="{{url_for('app.add_app')}}" class="btn btn-warning actions">Add</a> {% endif%}

</section>
{% endblock %}

app/templates/editApply.html
{% extends 'index.html' %} {% import 'macros.html' as macros %} {% block content %} {% if 'username' in session %}

<div class="container apps">
  <div class="row">

    <div class="col-xs-12 col-md-6 col-md-offset-3 panel panel-default">
      <legend>EditApplicaion</legend>
      {% call macros.render_form(form, action_url=url_for('app.edit_app',id=apply.id), action_text="Edit Application", class_="form-horizontal") %}
      <div class="col-md-6">
        {{ macros.input(form.company_name, type='text') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.date_apply, type='date') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.position, type='text') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.location, type='text') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.next_step, type='text') }}
      </div>
      <div class="col-md-6">
        {{ macros.input(form.contact, type='text') }}
      </div>
      <div class="col-md-12">
        {{ macros.input(form.job_board, type='text') }}
      </div>

      <div class="col-md-12">
        {{ macros.render_textarea(form.notes)}}
      </div>
      <div class="col-md-12 text-center">
        {% endcall %}
      </div>

    </div>
  </div>
  <script>
    $('#company_name').val("{{apply.company_name}}");
    $('#date_apply').val("{{apply.date_apply}}");
    $('#position').val("{{apply.position}}");
    $('#location').val("{{apply.location}}");
    $('#next_step').val("{{apply.next_step}}");
    $('#contact').val("{{apply.contact}}");
    $('#job_board').val("{{apply.job_board}}");
    $('#notes').val("{{apply.notes}}");

  </script>



</div>{% else %}
<h1>You be here. Your IP has been logged</h1> {% endif %}
</div>

{% endblock %}

app/templates/html_dependencies.html
<link rel="stylesheet" href="{{url_for('static', filename='node_modules/bootstrap/dist/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
<link rel="shortcut icon" href="/img/favicon.ico">
<script src="{{url_for('static', filename='node_modules/jquery/dist/jquery.min.js')}}" charset="utf-8"></script>
<script src="{{url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.min.js')}}" charset="utf-8"></script>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.css">
<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
<link rel="shortcut icon" href="/img/favicon.ico">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
</script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <title>Application Tracker</title>
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
          <a class="navbar-brand" href="{{ url_for('home')}}">Application Tracker</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{url_for('app.past_week')}}">Past 7 days</li>
	    <li class="dropdown">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if 'username' in session %}
            <li><a href="{{url_for('logout')}}">Logout</a></li>
            {% else %}
            <li><a href="{{url_for('login')}}">Login</a></li>
            {% endif %}

          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </nav>
    <div class="apps">
      {% block content %} {% endblock %}
    </div>
    <footer class="text-center">

      <div class="footer-below">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              Designed by JP Designs 316, Copyright &copy; 2017
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
</body>

</html>

app/templates/login.html
{% extends 'index.html' %} {% block content %}
<div class="container text-center">
  <div class="col-md-6 col-md-offset-3 panel  panel-default">
    <h1>Please login</h1>
    <br>
    <form action="" method="post" class="form-horizontal">
      <div class="form-group">
        <label for=username class="col-sm-2 control-label">Username:</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" placeholder="Username" name="username" value="{{
              request.form.username }}">
        </div>
      </div>
      <div class="form-group">
        <label for=username class="col-sm-2 control-label">Password:</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" placeholder="Password" name="password" value="{{
              request.form.password }}">
        </div>

      </div>

      <input class="btn btn-default" type="submit" value="Login">
    </form>


    {% if error %}
    <p class="error"><strong>Error:</strong> {{ error }}</p>
    {% endif %}
  </div>

</div>
{% endblock %}

app/templates/macros.html
{# Renders field for bootstrap 3 standards.

    Params:
        field - WTForm field
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_field(form.email, placeholder='Input email', type='email', value='') }}
#}
{% macro render_field(field, label_visible=true) -%}

    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {% if (field.type != 'HiddenField' and field.type !='CSRFTokenField') and label_visible %}
            <label for="{{ field.id }}" class="control-label">{{ field.label }}</label>
        {% endif %}
        {{ field(class_='form-control', **kwargs) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>
{%- endmacro %}

{% macro input(field, value='', type='', id='') -%}
    <label for="{{ field.id }}" class="control-label">{{ field.label }}</label>
    <input class="form-control" id="{{ field.id }}", type="{{ type }}" name="{{ field.id }}" value="{{
        value }}" size="{{ size }}">
{%- endmacro %}

{% macro render_checkbox_field(field) -%}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ field.label }}
        </label>
    </div>
{%- endmacro %}


{% macro render_textarea(field, class='form-control', value='', rows='80') -%}
<label for="{{ field.id }}" class="control-label">{{ field.label }}</label>
    <textarea class="form-control" id="{{ field.id }}"name="{{ field.id }}" >{{ value|e }}</textarea>
{%- endmacro %}

{% macro render_radio_field(field) -%}
    {% for value, label, _ in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}

{% macro render_form(form, action_url='', action_text='Submit', class_='', btn_class='btn btn-default app-btn') -%}

    <form method="POST" action="{{ action_url }}" role="form" class="{{ class_ }}">
        {{ form.hidden_tag() if form.hidden_tag }}
        {% if caller %}
            {{ caller() }}
        {% else %}
            {% for f in form %}
                {% if f.type == 'BooleanField' %}
                    {{ render_checkbox_field(f) }}
                {% elif f.type == 'RadioField' %}
                    {{ render_radio_field(f) }}
                {% else %}
                    {{ render_field(f) }}
                {% endif %}
            {% endfor %}
        {% endif %}
        <button type="submit" class="{{ btn_class }}">{{ action_text }} </button>
    </form>
{%- endmacro %}


{% macro job_type_select(field, value='', class='', id='') -%}
<label for="{{ field.id }}" class="control-label">{{ field.label }}</label>
 {% set job_types = ["Full-Time", "Part-Time", "Internship", "Contract"] %}
 <select name="{{field.id}}" class="{{class}}" id="{{id}}">
 {% for job_type in job_types %}
 <option value="{{job_type}}" {{'selected' if value==job_type else ''}}>{{job_type}}</option>
 {% endfor %}
 </select>
{%- endmacro %}

{% macro states_select(field, value='', class='', id='') -%}
 {% set states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA",
"ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
"OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"] %}
 <select name="{{location_state}}" class="{{class}}" id="{{id}}">
 {% for state in states %}
 <option value="{{state}}" {{'selected' if value==state else ''}}>{{state}}</option>
 {% endfor %}
 </select>
{%- endmacro %}

app/templates/modifyApply.old.html
{% extends 'index.html' %} {% block content %} {% if 'username' in session %}

<div class="container apps">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel education">
      <form method="post" class="form-horizontal" action="#">
        <div class="inner">
          <div>
            <fieldset class="form-group">
              <label for="">Company Name</label>
              <input type="text" class="form-control" name="company_name" {% if type=='edit' %} value="{{app.company_name}}" {% endif %}>
            </fieldset>
          </div>
          <div>
            <fieldset class="form-group">
              <label for="">Date: </label>
              <input type="date" class="form-control" name="date_apply" {% if type=='edit' %} value="{{app.date_apply}}" {% endif %}>
          </div>
          <div>
            <fieldset class="form-group">
              <label for="">Position</label>
              <input type="text" class="form-control" name="position" {% if type=='edit' %} value="{{app.position}}" {% endif %}>
          </div>
          <fieldset class="form-group">
            <label for="">Location:</label>
            <input type="text" class="form-control" name="location" {% if type=='edit' %} value="{{app.location}}" {% endif %}>
          </fieldset>
          <fieldset class="form-group">
            <label for="">Next Step:</label>
            <input type="text" class="form-control" name="next_step" {% if type=='edit' %} value="{{app.next_step}}" {% endif %}>
          </fieldset>
          <fieldset class="form-group">
            <label for="">Contact:</label>
            <input type="text" class="form-control" name="contact" {% if type=='edit' %} value="{{app.contact}}" {% endif %}>
          </fieldset>
          <fieldset class="form-group">
            <label for="">Where did you find this job?:</label>
            <input type="text" class="form-control" name="job_board" {% if type=='edit' %} value="{{app.job_board}}" {% endif %}>
          </fieldset>
          <fieldset class="form-group">
            <label for="">Notes:</label>
            <input type="text" class="form-control" name="notes" {% if type=='edit' %} value="{{app.notes}}" {% endif %}>
          </fieldset>
          <div>
            <div class="col-md-6">

            </div>
            <div class="col-md-6">
              <input type="submit" class="btn btn-primary" value="Submit">
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>{% else %}
<h1>You be here. Your IP has been logged</h1> {% endif %}
</div>

{% endblock %}

app/templates/modifySuggest.html
{% extends 'index.html' %} {% block content %}

<div class="container apps">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel education">
      <form method="post" class="form-horizontal" action="#">
        <div class="inner">
          <div>
            <fieldset class="form-group">
              <label for="">Position</label>
              <input type="text" class="form-control" name="position" {% if type=='edit' %} value="{{suggest.position}}" {% endif %}>
            </fieldset>
          </div>
          <div>
            <fieldset class="form-group">
              <label for="">Location: </label>
              <input type="test" class="form-control" name="location" {% if type=='edit' %} value="{{suggest.location}}" {% endif %}>
          </div>
          <div>
            <fieldset class="form-group">
              <label for="">Link to Application Page: </label>
              <input type="test" class="form-control" name="url" {% if type=='edit' %} value="{{suggest.url}}" {% endif %}>
          </div>
          <div>
            <fieldset class="form-group">
              <label for="">Suggested By</label>
              <input type="text" class="form-control" name="suggested_by" {% if type=='edit' %} value="{{suggest.suggested_by}}" {% endif %}>
          </div>

          <div>
            <div class="col-md-6">

            </div>
            <div class="col-md-6">
              <input type="submit" class="btn btn-primary" value="Submit">
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

app/templates/moreInfo.html
{% extends 'index.html' %} {% block content %}
<section class="app">
  <div class="row">
    <div class="col-md-4">
      <p><strong>Company Name: </strong> {{app.company_name}}</p>
      <p><strong>Location: </strong> {{app.location}}</p>
    </div>
    <div class="col-md-4">
      <p><strong>Position: </strong> {{app.position}}</p>
      <p><strong>Contact: </strong> {{app.contact}}</p>
    </div>
    <div class="col-md-4">
      <p><strong>Date of Application: </strong> {{app.date_apply}}</p>
      <p><strong>Found on: </strong> {{app.job_board}}</p>
    </div>
    <div class="col-md-12">
      <p><strong>Next Step: </strong> {{app.next_step}}</p>
      <p><strong>Note: </strong> {{app.notes}}</p>
    </div>
  </div>
  <a href="{{url_for('home')}}" class="btn btn-primary actions">Back</a> {% if 'username' in session %}
  <a href="{{url_for('app.edit_app',id=app.id)}}" class="btn btn-warning actions">Edit</a> {% endif %}
</section>

{% endblock %}

app/templates/suggestions.html
{% extends 'index.html' %} {% block content %}

<section class='apps'>
  <table class='table'>
    <thead class="thead-inverse">
      <tr>
        <th>Position</th>
        <th>Location</th>
        <th>URL</th>
        <th>Suggested By</th>
      </tr>
    </thead>
    <tbody>
      {% for suggest in suggestions %}
      <tr>
        <td>{{ suggest.position}}</td>
        <td>{{ suggest.location}}</td>
        <td>{{ suggest.url}}</td>
        <td>{{ suggest.suggested_by}}</td>

      </tr>
      {% endfor %}
  </table>
  <a href="{{url_for('suggest.add_suggest')}}" class="btn btn-warning actions">Add</a>

</section>
{% endblock %}